
language: rust
git:
  quiet: true

rust:
  - stable

os:
  - linux
  - osx

cache:
  cargo

before_script:
  - | # the package managers have very old versions, just build sdl2 from source
    travis_retry curl -L https://www.libsdl.org/release/SDL2-2.0.9.tar.gz | tar xz
    cd SDL2-2.0.9
    ./configure
    make
    sudo make install
    cd ..

script:
  - cargo build
  # there's a doctest difficulty here, see the appveyor file
  - cargo test --lib --tests
