
language: rust
git:
  quiet: true

rust:
  - stable

matrix:
  - os: linux
    before_script: - | # the package managers have very old versions, just build sdl2 from source
      travis_retry curl -L https://www.libsdl.org/release/SDL2-2.0.9.tar.gz | tar xz
      cd SDL2-2.0.9
      ./configure
      make
      sudo make install
      cd ..
  - os: osx
    before_script: - | # the package managers have very old versions, just build sdl2 from source
      travis_retry curl -L https://www.libsdl.org/release/SDL2-2.0.9.tar.gz | tar xz
      mv gcc-fat.sh SDL2-2.0.9/gcc-fat.sh
      cd SDL2-2.0.9
      ./configure CC="sh gcc-fat.sh" && make && rm -rf x86 x64
      make
      sudo make install
      cd ..

env:
  - LD_LIBRARY_PATH: "/usr/local/lib"

cache:
  cargo

script:
  - cargo build
  # there's a doctest difficulty here, see the appveyor file
  - cargo test --lib --tests
