
os: Visual Studio 2015

environment:
  # The pre-built SDL2 files that we have are for MSVC only.
  matrix:
    - channel: stable
      target: x86_64-pc-windows-msvc
      dllpath: lib/x64/SDL2.dll

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -y --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - cargo install bindgen
  - cp %dllpath% . # this is for some of our tests to run
  - rustc -vV
  - cargo -vV

build: false

test_script:
  # We cannot run doctests because rustdoc is silly and tries to interpret too
  # much stuff as code blocks and then dies when the "code blocks" don't contain
  # valid rust. https://github.com/rust-lang/rust/issues/59867 We should still
  # run all the other tests of course.

  # First we verify the default mode (cli mode)
  - cargo build
  - cargo test --lib --tests

  # Now we try a second time with the "use_bindgen_lib" feature
  - cargo build --features="use_bindgen_lib"
  - cargo test --lib --tests --features="use_bindgen_lib"
  
  # Now we double check that things go well with the "static" feature
  - cargo build --features="static_link_sdl2_use_with_caution"
  - cargo test --lib --tests --features="static_link_sdl2_use_with_caution"
