[package]
name = "fermium"
description = "An opinionated crate of sdl2 bindings."
repository = "https://github.com/Lokathor/fermium"
version = "0.0.3"
authors = ["Lokathor <zefria@gmail.com>"]
edition = "2018"
license = "Zlib"

links = "SDL2"
build = "build.rs"

[build-dependencies]
bindgen = "0.49"

[target."cfg(windows)".dependencies]
winapi = "0.3"

[target."cfg(not(windows))".dependencies]
libc = "0.2"
