[package]
name = "fermium"
version = "0.0.1"
authors = ["Lokathor <zefria@gmail.com>"]
edition = "2018"
license = "Zlib"

[dependencies]
libc = "0.2"

[build-dependencies]
bindgen = "0.49"

[features]
default = []
# Forces the crate to re-run bindgen. Do not use this from external crates.
force_bindgen = []
